
spring:
    # https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-data-import
    config:
      import: 'optional:configserver:'

  application:
    name: product-catalog

  cloud:
    config:
      uri: http://localhost:8888
